In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]


In [ ]:
a_sq = [i**2 for i in a]
print(a_sq)


[1, 4, 9, 16, 25]


In [ ]:
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr**2

array([ 1,  4,  9, 16, 25])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
[1,2,3,4,5] + 1


TypeError: ignored

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr + 1 # Its working like normal Maths, it has added 1 to all emenet of the list

array([2, 3, 4, 5, 6])

In [ ]:
np.arange(1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
l = list(range(1000000))


In [ ]:
%timeit [i**2 for i in l]


1 loop, best of 5: 316 ms per loop


In [ ]:
arr = np.arange(1000000)

In [ ]:
%timeit arr**2

The slowest run took 5.56 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 969 µs per loop


In [ ]:
np.__version__

'1.21.6'

In [ ]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1*2)

[1 2 3]
[2 4 6]


In [ ]:
# attribute/property
arr1.ndim

1

In [ ]:
arr1.shape

(3,)

In [ ]:
np.arange(2, 30, 3)


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [ ]:
np.arange(2, 20, 0.5)


array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. ,
       18.5, 19. , 19.5])

In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(1,10,10,endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [ ]:
np.array([1,2,3,4.0])

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4,5.5,'6.0'])

array(['1', '2', '3', '4', '5.5', '6.0'], dtype='<U32')

In [ ]:
arr1 = np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
len(arr1)

5

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
len(arr)

3

In [ ]:
m1 = np.arange(1,13)
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m1.ndim

1

In [ ]:
m2=m1.reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.ndim

2

In [ ]:
m3 =m1.reshape(3,3)

ValueError: ignored

In [ ]:
m3=m2.reshape(6,2)
m3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
m2.shape


(3, 4)

In [ ]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m3 =m2.flatten()
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m3.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Special Arrays

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,5),dtype='int')


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((5,2),dtype ='int')*3

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [ ]:
np.identity(5).astype('int')
3

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
m1 = np.arange(4, 16)
m1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
m1[6 : 10]


array([10, 11, 12, 13])

In [ ]:
m1[6 :-1]


array([10, 11, 12, 13, 14])

In [ ]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2[: , 1:-1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
m2[1,2]

7

In [ ]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(3).astype('int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.identity(4).astype('int')*5

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

In [ ]:
m1 = np.arange(4,16)
m1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
m1[-1]

15

In [ ]:
m1[2:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
m1[6:-2]

array([10, 11, 12, 13])

In [ ]:
m1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
m2=m1.reshape(3,4)
m2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
m2[2]

array([12, 13, 14, 15])

In [ ]:
m2[2,2]

14

In [ ]:
arr = np.arange(5, 25).reshape(4,5)
arr


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[1:,:2]

array([[10, 11],
       [15, 16],
       [20, 21]])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]
a

[1, 2, 6, 7, 8]

In [2]:
arr1=[1,2,3,4]
arr2=[5,6,7,8]
arr3=[9,10,11,12]

In [4]:
arr=np.array((arr1,arr2,arr3))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr.ndim

2

In [6]:
arr.shape

(3, 4)

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])